model:
  module_name: models.deep_network
  class_name: DeepModel
  dropout: 0.3
  hidden_dims:
    - 1024
    - 1024
#  save_checkpoint: path
#  load_checkpoint: model_weights/dense_1024_1024.tf
  learning_rate: 1e-3
  metrics:
    - accuracy

trainer:
  module_name: base.trainer
  class_name: BaseTrainer
  epochs: 10
  tensorboard_enabled: false
  workers: 2

devices:
  memory_growth: True
  log_device_placement: False

data:
  # augmentation:
  batch_size: 64
  image_shape: [128, 128]
#  directory:
#  subset_directory:
#  subsets:
#    train: sun_subset_train.csv
