model:
  module_name: models.deep_network
  class_name: DeepModel
  dropout: 0.3
#  dropout: 0.
  hidden_dims:
    - 2048
    - 1024
  learning_rate: 1.0e-3
  metrics:
    - accuracy

trainer:
  module_name: trainers.reduce_lr_on_plateau
  class_name: ReduceLROnPlateauTrainer
  epochs: 10
  tensorboard_enabled: true
  workers: 3
  experiment_name: deep_network_lr_reducing
  reduce_lr_on_plateau:
    patience: 3
    factor: 0.1
    min_delta: 0.001
    monitor: val_loss
  model_checkpoint:
    filepath: "model_weights/deep/deep_smaller_input"
    save_best_only: true
    verbose: 1

devices:
  memory_growth: true
  log_device_placement: false

data:
  # augmentation:
  batch_size: 128
  image_shape: [64, 64]
#  subset_directory:
  subsets:
    train: sun_half_train.csv
#    valid: sun_half_valid.csv
