model:
  module_name: models.deep_network
  class_name: DeepModel
  dropout: 0.3
  hidden_dims:
    - 1024
    - 1024
  save_checkpoint: model_weights/dense_1024_1024_lr_reducing.tf
  learning_rate: 1e-3
  metrics:
    - accuracy

trainer:
  module_name: trainers.reduce_lr_on_plateau
  class_name: ReduceLROnPlateauTrainer
  epochs: 10
  tensorboard_enabled: false
  workers: 2
  reduce_lr_on_plateau:
    patience: 3
    factor: 0.1
    min_delta: 0.01
    monitor: val_loss

devices:
  memory_growth: True
  log_device_placement: False

data:
  # augmentation:
  batch_size: 64
  image_shape: [128, 128]
#  directory:
#  subset_directory:
